name: Build and Push Docker Image

on:
  push:
    branches:
      - dev # Trigger workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{Js?69C3a.,mD?AF}}" | docker login -u "${{minimonster32}}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
